# General settings
API_TOKEN = 'TOKEN'
TIME_LIMIT = 300

# Timby settings
HOST = '0.0.0.0'
PORT = 5000

# Database settings
MYSQL_HOST = 'HOST'
MYSQL_DATABASE = 'DATABASE'
MYSQL_USER = 'USER'
MYSQL_PASSWORD = 'PASSWORD'
